branches:
  only:
    - "master"

language: generic

os: linux
dist: bionic

services:
  - xvfb

before_install:
  - curl -fsSLo- https://raw.githubusercontent.com/felipecassiors/scripts/master/install_virtualbox.sh | bash
  - curl -fsSLo- https://raw.githubusercontent.com/felipecassiors/scripts/master/install_vagrant.sh | bash

script:
  - vagrant up

before_deploy:
  - nvm install lts/*
  - npm install -g semantic-release-vagrant@beta

deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    all_branches: true
